#!/usr/bin/fish
set -l desktop_home (if set -q XDG_CONFIG_HOME; echo -n $XDG_CONFIG_HOME; else; echo -n $HOME/.config; end)/i3

compton -b
dunst & disown
redshift & disown
nm-applet & disown
blueman-applet & disown
if test -f $desktop_home/wallpaper
    feh --bg-scale $desktop_home/wallpaper
end    

